Change structure
NightNineNeighbor/Book-manager pull request #11
Opened 2019-02-12 11:35 UTC by NightNineNeighbor

* 객체의 구조를 변경
* 패키지 정리
* 객체 이름 개선

2019-02-12 12:19 UTC, javajigi requested changes
뭔가 State에 찜찜함이 있는데 정확히 어떻게 개선해야할지 잘 모르겠네.

2019-02-12 12:19 UTC, javajigi commented on src/main/java/com/group/artifact/state/BookInfoState.java
> +public class BookInfoState implements NeedBookNameState {
NeedBookNameState을 구현하는 State 클래스에 중복이 많이 보인다.
중복을 제거할 수 있는 방법은 없을까?

2019-02-12 12:19 UTC, javajigi commented on src/main/java/com/group/artifact/state/DoNothing.java
> +    public String doService(SlackService service, MessageVo messageVo, ChatBotState chatBotState) {
메소드 인자로 `SlackService service, MessageVo messageVo, ChatBotState chatBotState`가 전달되는 것이 뭔가 꺼림직한데 다른 방법은 없을까? 뭔지 모를 찜찜함.

2019-02-12 12:19 UTC, javajigi commented on src/main/java/com/group/artifact/state/DoNothing.java
> +import com.group.artifact.state_collection.ChatBotState;
패키지 이름에 "_"를 쓰지 않으면 어떨까?

2019-02-12 12:19 UTC, javajigi commented on src/main/java/com/group/artifact/vo/MessageVo.java
> +    public String getHashKey() {
hashCode() 메소드를 오버라이드하고 이 메소드를 사용해도 되지 않을까?

2019-02-19 07:38 UTC, NightNineNeighbor commented
* hashCode() 오버라이드 피드백 대신 getSlackId()로 바꿨습니다. 제 생각으로는 slackId를 키로 쓴다는 것을 명시하는게 좋을 것 같아서 입니다.

2019-02-20 09:19 UTC, merged